### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by RAR27** [ifreund/river#88]
Hey, I came across this window manager and I really want to try it out, mostly because of the use of wayland (and I don't really i3/sway) but I can't seem to build it. This is the error that I get. 
```
In file included from /home/rehan/Downloads/river/protocol/river-control-unstable-v1-protocol.c:1:
/home/rehan/Downloads/river/protocol/river-control-unstable-v1.xml:3:10: fatal error: 'array' file not found
#include <array>
         ^~~~~~~
1 error generated.
```
I've been googling to try and fix it myself, but having no luck.
Thanks in advance!

**Comment by ifreund** [comment]
What distro are you running? Could you confirm that you have the development version of libwayland installed? If so what version?

**Comment by RAR27** [comment]
Ok so I just installed the development version, and it got past that error. However, now it gives me this:
```
//usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml:1: parser error : Start tag expected, '<' not found
#pragma once
^
Failed to read XML
The following command terminated unexpectedly:
wayland-scanner private-code //usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml protocol/xdg-shell-protocol.c 
```
I'm on void linux.

**Comment by ifreund** [comment]
I'm also on void linux, so you should definitely be able to get it building. As mentioned in the readme, you also need `wayland-protocols` installed which I suspect should fix that error.

**Comment by RAR27** [comment]
I have installed `wayland-protocols` as well as the other software in the README. Would I need to install the devel versions of some of that software?

**Comment by ifreund** [comment]
Indeed, you will need the `-devel` version of all packages listed which have one.

**Comment by RAR27** [comment]
Just installed all the devel packages available, and still get the same error.

**Comment by RAR27** [comment]
I actually just figured it out. I'm not sure why or how, but the xml file that wayland-scanner was pointing to was filled with some random c/c++ code for whatever reason. I removed the entire directory and cloned the git repo again, and it built just fine. Thanks for your help!

**Comment by ifreund** [comment]
Glad it worked out, no problem!
